---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 30/09/23 17:21
---

local characterKilledZombies = require("CharacterKilledZombies")
local characterLifeTime = require("CharacterLifeTime")
local characterBoost = require("CharacterBoost")
local characterMultiplier = require("CharacterMultiplier")
local characterNutrition = require("CharacterNutrition")
local characterPerkDetails = require("CharacterPerkDetails")
local characterTrait = require("CharacterTrait")
local characterRecipe = require("CharacterRecipe")
local debugDiagnostics = require("lib/DebugDiagnostics")
local dataValidator = require("lib/DataValidator")
local modDataManager = require("lib/ModDataManager")
local characterPz = require("lib/CharacterPZ")
local perkFactoryPZPz = require("lib/PerkFactoryPZ")
local isoPlayerPZ = require("lib/IsoPlayerPZ")
local characterLib = require("CharacterLib")
require("lib/CharacterBaseObj")

---@param character IsoGameCharacter
local function character_TDD(character)


    --characterPz.setTraitsPerk_PZ(character,"HardOfHearing" )
    --characterPz.setTraitsPerk_PZ(character,"SlowReader" )
    --characterPz.setTraitsPerk_PZ(character,"Handy" )
    --
    -- Check trait
    characterTrait.writeBook(character)
    characterTrait.readBook(character)

    ---@type CharacterBaseObj
    local CharacterTraitObj = CharacterBaseObj:new()
    CharacterTraitObj = characterLib.getTraitsPerk(character)


    -------------------------------


    -- Check recipe
    characterRecipe.writeBook(character)
    characterRecipe.readBook(character)

    local recipe = "Make Pizza"
    CharacterObj = characterLib.getKnownRecipes(character)

    if not CharacterObj:getRecipes()[1] then
        debugDiagnostics.checkTest(false, true, "List getKnownRecipes is empty")
    end

    for _, v in pairs(CharacterObj:getRecipes()) do
        debugDiagnostics.checkTest(v,
                recipe, "Recipe")
    end

    -------------------------------

    -- Check Perk Details
    characterPerkDetails.writeBook(character)
    characterPerkDetails.readBook(character)

    -- Check Perk Details: check Profession
    debugDiagnostics.checkTest(characterPz.getProfession_PZ(character),
            debugDiagnostics.Profession.CARPENTER, "Profession" )

    -- Check Perk Details: Perk Level
    debugDiagnostics.checkTest( characterPz.getXp(character, Perks.Fitness),
            37500, "PerkLevel Fitness")
    debugDiagnostics.checkTest( characterPz.getXp(character, Perks.Strength),
            37500, "PerkLevel Strength")
    debugDiagnostics.checkTest( characterPz.getXp(character, Perks.Woodwork),
            1275, "PerkLevel Woodwork")
    debugDiagnostics.checkTest( characterPz.getXp(character, Perks.Maintenance),
            75, "PerkLevel Maintenance")
    debugDiagnostics.checkTest( characterPz.getXp(character, Perks.SmallBlunt),
            75, "PerkLevel SmallBlunt")

    -----------------------------

    -- check Calories
    characterNutrition.writeBook(character)
    characterNutrition.readBook(character)

    debugDiagnostics.checkTest(isoPlayerPZ.getCalories_PZ(),
            1500, "Calories")

    -- check Weight
    debugDiagnostics.checkTest(isoPlayerPZ.getWeight_PZ(),
            92, "Weight")
    ---------------------------

    -- Check multiplier
    characterMultiplier.writeBook(character)
    characterMultiplier.readBook(character)

    local multiplier_PZ =
    characterPz.getMultiplier_PZ(character, Perks.Cooking)

    multiplier_PZ = dataValidator.trunkFloatTo2Decimal(multiplier_PZ)

    local multiplier = 1.0
    debugDiagnostics.checkTest(multiplier_PZ,
            multiplier, "Multiplier")

    ---------------------------

    -- Check Life Time
    ---@param lifeTime double
    isoPlayerPZ.setHoursSurvived_PZ(1)

    characterLifeTime.writeBook(character)
    characterLifeTime.readBook(character)

    debugDiagnostics.checkTest( isoPlayerPZ.getHoursSurvived_PZ(),
            1, "Life Time")

    ---------------------------

    -- Check Zombie Kills
    characterKilledZombies.writeBook(character)
    characterKilledZombies.readBook(character)

    debugDiagnostics.checkTest( characterPz.getZombieKills_PZ(character),
            15, "Killed Zombies")

    ---------------------------

    -- Check Perk Boost
    characterBoost.writeBook(character)
    characterBoost.readBook(character)

    debugDiagnostics.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Fitness),
            3, "PerkBoost Fitness")
    debugDiagnostics.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Strength),
            3, "PerkBoost Strength")
    debugDiagnostics.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Woodwork),
            3, "PerkBoost Woodwork")

    -------------------------
end

---@param character IsoGameCharacter
local function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > EraseRewind_RPG TDD \n")
        ---
        debugDiagnostics.setVerbose(false)
        debugDiagnostics.deleteCharacter()
        debugDiagnostics.createCharacter()
        ---

        character_TDD(character)
        debugDiagnostics.displayTest()
    end
end

---@param character IsoGameCharacter
local function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h >  \n")

    end
end

---@param character IsoGameCharacter
local function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j >  \n")
        -----
        --debugDiagnostics.setVerbose(false)
        --debugDiagnostics.deleteCharacter()
        --debugDiagnostics.createCharacter()
        -----
        --
        --character_TDD()
        --
        --debugDiagnostics.printLine()
        --debugDiagnostics.displayTest()
        --debugDiagnostics.printLine()
    end
end

---@param character IsoGameCharacter
local function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k >  \n")

    end
end

---@param character IsoGameCharacter
local function key16(character, key)
    if key == 16 then -- <<<< q
        print("Key = q > kill Character \n")
        character:die()
    end
end

---@param character IsoGameCharacter
local function key17(character, key)
    if key == 17 then -- <<<< w
        print("Key = w >   \n")

    end
end

---@param character IsoGameCharacter
local function key18(character, key)
    if key == 18 then -- <<<< e
        print("Key = e >  \n")

    end
end

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    --key16(character, key) -- q kill character
    --key17(character, key) -- w
    --key18(character, key) -- e
    --key34(character, key) -- g
    --key35(character, key) -- h
    --key36(character, key) -- j
    --key37(character, key) -- k
end

Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)