---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 12/05/23 15:30
---

local dbgLeleLib = require("lib/DbgLeleLib")
local characterPz = require("lib/CharacterPZ")
local isoPlayerPZ = require("lib/IsoPlayerPZ")
local character = getPlayer()

local function checkCharacter()
    character = getPlayer()

    dbgLeleLib.checkTest(characterPz.getProfession_PZ(character),
            dbgLeleLib.EnumProfession.CARPENTER, "Profession" )

    dbgLeleLib.checkTest( characterPz.getXp(character, Perks.Fitness),
            37500, "PerkLevel Fitness")
    local db1 = characterPz.getXp(character, Perks.Fitness)

    dbgLeleLib.checkTest( characterPz.getXp(character, Perks.Strength),
            37500, "PerkLevel Strength")
    dbgLeleLib.checkTest( characterPz.getXp(character, Perks.Woodwork),
            1275, "PerkLevel Woodwork")
    dbgLeleLib.checkTest( characterPz.getXp(character, Perks.Maintenance),
            75, "PerkLevel Maintenance")
    dbgLeleLib.checkTest( characterPz.getXp(character, Perks.SmallBlunt),
            75, "PerkLevel SmallBlunt")

    dbgLeleLib.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Fitness),
            3, "PerkBoost Fitness")
    dbgLeleLib.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Strength),
            3, "PerkBoost Strength")
    dbgLeleLib.checkTest( characterPz.getPerkBoost_PZ(character, Perks.Woodwork),
            3, "PerkBoost Woodwork")

    dbgLeleLib.checkTest( characterPz.getZombieKills_PZ(character),
            15, "Zombie")

    dbgLeleLib.checkTest(isoPlayerPZ.getHoursSurvived_PZ(),
            10, "HoursSurvived")
    dbgLeleLib.checkTest(isoPlayerPZ.getCalories_PZ(),
            1500, "HoursSurvived")
    dbgLeleLib.checkTest(isoPlayerPZ.getWeight_PZ(),
            92, "Weight")

end

-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
local function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > writeBook \n")
        dbgLeleLib.deleteCharacter()
        dbgLeleLib.createCharacter()
        writeBook(character)
        readBook(character)
        checkCharacter()
    end
end

---@param character IsoGameCharacter
local function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > delete \n")
        character:die()
    end
end

-- https://theindiestone.com/forums/index.php?/topic/9799-key-code-reference/
local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    if key == 34 then key34(character, key)  end -- <<<< g
    --if key == 35 then key35(character, key)  end -- <<<< h
    --if key == 36 then key36(character, key)  end -- <<<< j
    if key == 37 then key37(character, key)  end -- <<<< kill
    --if key == 16 then key16(character, key)  end -- <<<< 1
    --if key == 17 then key17(character, key)  end -- <<<< 2

end

-- Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
