---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 30/09/23 17:07
---

--- https://zomboid-javadoc.com/41.78/

--local zombieKills = {}
--zombieKills = "1056"
--
--print(zombieKills)

-- project zomboid, get inventory items
--local player = getPlayer()
--local inventory = player:getInventory()
--local items = inventory:getItems()
--print(items)

-- project zomboid, get mods activeMods
--local activeMods = require("ActiveMods")
--print("isModActive = " .. activeMods.getMods() .. "\n")


