	--EraseRewindRPG = "EraseRewindRPG",
	--EraseRewindRPG_SetDate = "Custom option #1",
	--EraseRewindRPG_SetDate_tooltip = "Tooltip for custom option #1",
    --
	--EraseRewindRPG_SetTimeOfReadBook = "Custom option #1",
	--EraseRewindRPG_SetTimeOfReadBook_tooltip = "Tooltip for custom option #1",
    --

    --Sandbox_EraseRewindRPG = "EraseRewindRPG",
    --Sandbox_EraseRewindRPG_SetDate = "Custom option #1",
    --Sandbox_EraseRewindRPG_SetDate_tooltip = "Tooltip for custom option #1",
    --
    --Sandbox_EraseRewindRPG_SetTimeOfReadBook = "Custom option #1",
    --Sandbox_EraseRewindRPG_SetTimeOfReadBook_tooltip = "Tooltip for custom option #1",