---------------------------------------------------
--
--local date = "Fri Jul 09 09:43:41 CEST 1993"
-----@type table
--
--local month = {
--    Jan = 1, Feb = 2, Mar = 3, Apr = 4, May = 5, Jun = 6,
--    Jul = 7, Aug = 8, Sep = 9, Oct = 10, Nov = 11, Dec = 12
--}
--
--local dateParts = {}
--
----- **Extract date**
--for datePart in date:gmatch("%S+") do
--   table.insert(dateParts, datePart)
--end
--
--for hour, minute, second in date:gmatch("(%d+):(%d+):(%d+)") do
--    --table.insert(dateParts, timePart)
--    --print(timePart)
--    dateParts[7] = hour
--    dateParts[8] = minute
--    dateParts[9] = second
--end
--
------------------------------------------------------------------
--
----@type table
----- - "Fri Jul 09 09:43:41 CEST 1993"
--local datePartsConverted = {
--    ---@type string
--    day = dateParts[1],
--    ---@type number
--    dayOfWeek = tonumber(dateParts[3]),
--    ---@type string
--    month = dateParts[2],
--    ---@type number
--    monthOfYear = month[dateParts[2]],
--    ---@type string
--    cest = dateParts[5],
--    ---@type number
--    year = tonumber(dateParts[6]),
--    ---@type number
--    hour = tonumber(dateParts[7]),
--    ---@type number
--    min = tonumber(dateParts[8]),
--    ---@type number
--    sec = tonumber(dateParts[9]),
--}
--
----@type table
--local dateConverted = {
--    ---@type number
--    year = datePartsConverted.year,
--    ---@type number
--    month = datePartsConverted.monthOfYear,
--    ---@type number
--    day = datePartsConverted.dayOfWeek,
--    ---@type number
--    hour = datePartsConverted.hour,
--    ---@type number
--    min = datePartsConverted.min,
--    ---@type number
--    sec = datePartsConverted.sec,
--}
--
--print("dateConverted.dayOfWeek " .. dateConverted.day)
--print("dateConverted.monthOfYear " .. dateConverted.month)
--print("dateConverted.year " .. dateConverted.year)
--print("dateConverted.hour " .. dateConverted.hour)
--print("dateConverted.min " .. dateConverted.min)
--print("dateConverted.sec " .. dateConverted.sec)
--local value1 = os.time(dateConverted)
--print("value1 " .. value1)
--print("------------------------------")
--
--print("datePartsConverted.day " .. datePartsConverted.day)
--print("datePartsConverted.month " .. datePartsConverted.month)
--print("datePartsConverted.monthOfYear " .. datePartsConverted.monthOfYear)
--print("datePartsConverted.year " .. datePartsConverted.year)
--print("datePartsConverted.hour " .. datePartsConverted.hour)
--print("datePartsConverted.min " .. datePartsConverted.min)
--print("datePartsConverted.sec " .. datePartsConverted.sec)
--print("datePartsConverted.cest " .. datePartsConverted.cest)
--
----local value2 = os.time(datePartsConverted)
--
--
--
--
--
--
--
------------------------------------------------
--
--
------@type table
----local datePartsConverted = {
----    day = dateParts[1],
----    ---@field string
----    month = dateParts[2],
----    ---@field int
----    monthOfYear = dateParts[3],
----    ---@field string
----    cest = dateParts[5],
----    ---@field number
----    year = tonumber(dateParts[6]),
----    ---@field number
----    hour = dateParts[7],
----    ---@field number
----    min = dateParts[8],
----    ---@field number
----    sec = dateParts[9],
----}
----
----print(datePartsConverted.day)
----print(datePartsConverted.month)
----print(datePartsConverted.monthOfYear)
----print(datePartsConverted.year)
----print(datePartsConverted.hour)
----print(datePartsConverted.min)
----print(datePartsConverted.sec)
----print(datePartsConverted.cest)
----
----local s = os.time(datePartsConverted)