---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 10/05/23 15:11
---

---@class ModDataManager

local ModDataManager = {}

--- **Save ModData to Harddisk**
---@param nameFile String
---@param values table
---@return void
--- - ModData : zombie.world.moddata.ModData
function ModDataManager.save(nameFile, values)
    if not nameFile or not values then
        return nil
    end

    ModData.create(nameFile)
    ModData.add(nameFile, values)
end

--- **Read ModData**
---@param nameFile String
---@return table
--- - ModData : zombie.world.moddata.ModData
function ModDataManager.read(nameFile)
    if not nameFile then
        return nil
    end

    local lines = {}
    lines = ModData.get(nameFile)

    local conversionTotable = {}

    for _, v in pairs(lines) do
        table.insert(conversionTotable, v)
    end

    return conversionTotable
end

--- **Is modData Exists**
---@param nameFile String
---@return boolean
--- - ModData : zombie.world.moddata.ModData
function ModDataManager.isExists(nameFile)
    if not nameFile then
        return nil
    end

    return ModData.exists(nameFile)
end

--- **Remove modData**
---@param nameFile String
---@return void
--- - ModData : zombie.world.moddata.ModData
function ModDataManager.remove(nameFile)
    if not nameFile then
        return nil
    end

    ModData.remove(nameFile)
end

return ModDataManager