---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 30/09/23 19:22
---

--- LAST UPDATE 05-09-2023

---@class CharacterManagement

local CharacterManagement = {}

local characterBoost = require("character/CharacterBoost")
local characterKilledZombies = require("character/CharacterKilledZombies")
local characterLifeTime = require("character/CharacterLifeTime")
local characterMultiplier = require("character/CharacterMultiplier")
local characterNutrition = require("character/CharacterNutrition")
local characterPerkDetails = require("character/CharacterPerkDetails")
local characterRecipe = require("character/CharacterRecipe")
local characterTrait = require("character/CharacterTrait")
local errHandler = require("lib/ErrHandler")
local pageBook = require("book/PageBook")
local modDataManager = require("lib/ModDataManager")
local patchSurvivalRewards = require("patch/survivalRewards/PatchSurvivalRewards")

--- **Remove all Mod Data**
---@return void
function CharacterManagement.removeAllModData()
    modDataManager.remove(pageBook.Character.BOOST)
    modDataManager.remove(pageBook.Character.CALORIES)
    modDataManager.remove(pageBook.Character.LIFE_TIME)
    modDataManager.remove(pageBook.Character.MULTIPLIER)
    modDataManager.remove(pageBook.Character.RECIPES)
    modDataManager.remove(pageBook.Character.PERK_DETAILS)
    modDataManager.remove(pageBook.Character.PROFESSION)
    modDataManager.remove(pageBook.Character.READ_ONCE_BOOK)
    modDataManager.remove(pageBook.Character.TRAITS)
    modDataManager.remove(pageBook.Character.TIMED_BOOK)
    modDataManager.remove(pageBook.Character.WEIGHT)
    modDataManager.remove(pageBook.Character.KILLED_ZOMBIES)

    ------- PATCH ------------
    --- survivalRewards 2797671069
    --- https://steamcommunity.com/sharedfiles/filedetails/?id=2797671069&searchtext=2797671069

    if patchSurvivalRewards.isModActive() then
        patchSurvivalRewards.removeMil_kill_Reached()
    end
    --------------------------
end

--- **Read Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterManagement.readBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterManagement.readBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    characterPerkDetails.readBook(character)
    characterTrait.readBook(character)
    characterKilledZombies.readBook(character)
    characterLifeTime.readBook()
    characterNutrition.readBook()
    characterRecipe.readBook(character)
    characterBoost.readBook(character)
    characterMultiplier.readBook(character)

    ------- PATCH ------------
    --- survivalRewards 2797671069
    --- https://steamcommunity.com/sharedfiles/filedetails/?id=2797671069&searchtext=2797671069

    if patchSurvivalRewards.isModActive() then
        patchSurvivalRewards.createMil_kill_Reached(character)
    end
    --------------------------

    CharacterManagement.removeAllModData()
end

--- **Write Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterManagement.writeBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterManagement.writeBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    characterPerkDetails.writeBook(character)
    characterKilledZombies.writeBook(character)
    characterLifeTime.writeBook()
    characterNutrition.writeBook()
    characterTrait.writeBook(character)
    characterRecipe.writeBook(character)
    characterBoost.writeBook(character)
    characterMultiplier.writeBook(character)

    ------- PATCH ------------
    --- survivalRewards 2797671069
    --- https://steamcommunity.com/sharedfiles/filedetails/?id=2797671069&searchtext=2797671069

    if patchSurvivalRewards.isModActive() then
        patchSurvivalRewards.writeMil_kill_ReachedToHd(character)
    end
    --------------------------
end

return CharacterManagement