---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 12/10/23 20:51
---

require "ISUI/ISInventoryPaneContextMenu"
local debugDiagnostics = require("lib/DebugDiagnostics")
local readOnceBook = require("book/ReadOnceBook")
local timedBook = require("book/TimedBook")
local chooseBook = require("ChooseBook")

---@type string
local translation

--- **Save player**
---@param item InventoryItem
---@param character IsoGameCharacter
---@return void
--- - InventoryItem : zombie.inventory.InventoryItem
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function onSavePlayer(item, character)
    ---@type string
    local openBook = "OpenBook"

    ---@type string
    local closeBook = "CloseBook"

    --- **Translate to selected language**
    translation = getText( "ContextMenu_WrittenBook") .. " - " ..
            getText("ContextMenu_RebootClient")

    --- **Play sound**
    character:playSound(openBook)

    ---@type boolean
    local flag01 = false

    if chooseBook.isCorrectBook(item, "ReadOnceBook") then

        --- **Write mod-data - Write book**
        readOnceBook.writeBook(character, item)
        flag01 = true
    elseif chooseBook.isCorrectBook(item, "TimedBook") then

        --- **Write mod-data - Write book**
        if timedBook.writeBook(character) then
            flag01 = true
        else
            --- **You can't transcribe this book yet**
            translation = getText( "ContextMenu_ToEarly")
            flag01 = false
        end
    end

    --- **If true add player name to read Once Book journal**
    if flag01 then
        item:setName(item:getName() .. " - " .. character:getFullName() )
    end

    --- **Say message**
    character:Say(translation)

    --- **Play sound**
    character:playSound(closeBook)
end

--- **Write book**
---@param character IsoGameCharacter
---@param context ISInventoryPaneContextMenu
---@param items InventoryItem
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - ISInventoryPaneContextMenu : zombie.ui.ISInventoryPaneContextMenu
--- - InventoryItem : zombie.inventory.InventoryItem
local function addSaveContext(character, context, items)
    --- **Translate to selected language**
    translation = getText("ContextMenu_TranscribeBook")

    --- **Update all the characteristics of the character**
    character = debugDiagnostics.characterUpdate()

    ---@type InventoryItem
    --- **Retrive the selected item from the GUI inventory**
    local item = items[1].items[1]

    --- **If a book create a context menu**
    if chooseBook.isBook(item)  then
        context:addOption(translation, item, onSavePlayer, character)
    end
end

Events.OnPreFillInventoryObjectContextMenu.Add(addSaveContext)