---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 07/10/23 12:25
---

---@class ReadOnceBook

local ReadOnceBook = {}

local characterManagement = require("character/CharacterManagement")
local errHandler = require("lib/ErrHandler")
local modDataManager = require("lib/ModDataManager")
local pageBook = require("book/PageBook")

--- **Read Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function ReadOnceBook.readBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("OneTimeBookRead.readBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    characterManagement.readBook(character)
end

--- **Write Book**
---@param character IsoGameCharacter
---@return boolean
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function ReadOnceBook.writeBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("OneTimeBookRead.writeBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end
    local flag = true

    if modDataManager.isExists(pageBook.Character.READ_ONCE_BOOK) then
    flag = false
    end


    if flag then
        local lines = {}
        table.insert(lines, "true")
        --- **Remove scheduled BookRead date to mod data**
        modDataManager.remove(pageBook.Character.READ_ONCE_BOOK)

        --- **Save scheduled BookRead date to mod data**
        modDataManager.save(pageBook.Character.READ_ONCE_BOOK, lines)

        --- **Write Book**
        characterManagement.writeBook(character)
    end
return flag
end

return ReadOnceBook