---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

local characterPz = require("lib/CharacterPZ")
local modDataX = require("lib/ModDataX")
local characterLib = require("CharacterLib")

require("EnumModData")
require("lib/CharacterObj")
---Read Trait From Hd
---@return table
local function readTraitFromHd()
    return modDataX.readModata(EnumModData.CHARACTER_TRAITS)
end

---Create Trait
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createTrait(character)
    if not modDataX.isExists(EnumModData.CHARACTER_TRAITS) then
        return nil
    end

    local trait = {}
    trait = readTraitFromHd(character)

    if not trait then
        return nil
    end

    characterPz.removeAllTraits_PZ(character)

    for _, v in pairs(trait) do
        characterPz.setTraitsPerk_PZ(character, v)
    end
end

---Write Trait To Hd
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeTraitToHd(character)
    modDataX.remove(EnumModData.CHARACTER_TRAITS)

    local trait = CharacterObj:new()
    trait = characterLib.getTraitsPerk(character)

    modDataX.saveModata(EnumModData.CHARACTER_TRAITS,
            trait:getTraits())
end