---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

local characterLib = require("CharacterLib")
local characterPz = require("lib/CharacterPZ")
local modDataX = require("lib/ModDataX")

require("EnumModData")
require("lib/CharacterObj")

---Read Recipe From Hd
---@return CharacterObj getRecipes table string
local function readRecipeFromHd()
    local characterKnowRecipe =
        modDataX.readModata(EnumModData.CHARACTER_RECIPES )

    local CharacterObj01 = CharacterObj:new()

    for _, v in pairs(characterKnowRecipe) do
        CharacterObj01:addRecipe(v)
    end

    return CharacterObj01
end

---Delete Recipe
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
local function deleteRecipe(character)
    local characterKnowRecipe = CharacterObj:new()

    characterKnowRecipe = characterLib.getKnownRecipes(character)

    for _, v in pairs(characterKnowRecipe:getRecipes()) do
        characterPz.removeKnowRecipe_PZ(character, v)
    end
end

---Create Recipe
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createRecipe(character)
    if not modDataX.isExists(EnumModData.CHARACTER_RECIPES) then
        return nil
    end
    local CharacterObj01 = CharacterObj:new()

    CharacterObj01 = readRecipeFromHd(character)
    deleteRecipe(character)

    for _, v in pairs(CharacterObj01:getRecipes()) do
        characterPz.addKnownRecipe(character, v)
    end
end

---Write Recipe To Hd
function writeRecipeToHd(character)
    local knownRecipesObj = CharacterObj:new()
    knownRecipesObj =  characterLib.getKnownRecipes(character)

    local lines = {}

    for _, v in pairs(knownRecipesObj:getRecipes()) do
        table.insert(lines, v)
    end

    lines = {}

    modDataX.saveModata(EnumModData.CHARACTER_RECIPES, lines)
end