---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

local nameModData = "characterLifeTime"

---Read Life Time From Hd
function readLifeTimeFromHd()
    local lines = {}

    lines = ModData.get(nameModData)
    return lines[1]
end

---Set Life Time
---@param lifeTime double
function setLifeTime(lifeTime)
    IsoPlayer.getInstance():setHoursSurvived(lifeTime)
end

---Get Life Time
---@return double
function getLifeTime()
    return IsoPlayer.getInstance():getHoursSurvived()
end

---Create Life Time
function createLifeTime()
    local lifeTime = readLifeTimeFromHd()
    setLifeTime(lifeTime)
end

---Write Life Time To Hd
function writeLifeTimeToHd()
    ModData.remove(nameModData)

    local lifeTime = getLifeTime()

    local lines = {}
    table.insert(lines, lifeTime)

    ModData.add(nameModData, lines)
end