---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---
require("media.lua.client.EnumModData")

---Read Zombies Killed From Hd
---@return int
local function readZombieKillsFromHd()
    return modDataReadSingleValue( EnumModData.CHARACTER_ZOMBIE_KILLS)
end

---Create Zombies Kills
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createZombieKills(character)
    if not modDataIsExist(EnumModData.CHARACTER_ZOMBIE_KILLS) then
        return nil
    end

    local zombieKills = readZombieKillsFromHd()
    setZombieKills_PZ(character, zombieKills)
end

---Write Zombies Kills To Hd
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeZombieKillsToHd(character)
    modDataInsertSingleValue(EnumModData.CHARACTER_ZOMBIE_KILLS,
            getZombieKills_PZ(character) )
end