---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

require("media.lua.client.EnumModData")

---Read Life Time From Hd
---@return double
local function readLifeTimeFromHd()
    return modDataReadSingleValue(EnumModData.CHARACTER_LIFE_TIME)
end

---Create Life Time
function createLifeTime()
    if not modDataIsExist(EnumModData.CHARACTER_LIFE_TIME) then
        return nil
    end

    ---@type double
    local lifeTime = readLifeTimeFromHd()
    setHoursSurvived_PZ(lifeTime)
end

---Write Life Time To Hd
function writeLifeTimeToHd()
    modDataInsertSingleValue(EnumModData.CHARACTER_LIFE_TIME, getHoursSurvived_PZ())
end