---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

---@class CharacterLifeTime

local CharacterLifeTime = {}

local isoPlayerPZ = require("lib/IsoPlayerPZ")
local pageBook = require("PageBook")
local modDataManager = require("lib/ModDataManager")

--- **Read Life Time From Hd**
---@return table double
local function readLifeTimeFromHd()
    return modDataManager.read(pageBook.Character.LIFE_TIME)
end

--- **Create Life Time**
function CharacterLifeTime.readBook()
    if not modDataManager.isExists(pageBook.Character.LIFE_TIME) then
        return nil
    end

    ---@type table
    ---@return double
    local lifeTime = {}
    lifeTime = readLifeTimeFromHd()

    for i, v in pairs(lifeTime) do
        isoPlayerPZ.setHoursSurvived_PZ(v)
    end

end

--- **Write Life Time To Hd**
function CharacterLifeTime.writeBook()
    modDataManager.remove(pageBook.Character.LIFE_TIME)

    ---@type table
    local hoursSurvived = {}
    table.insert(hoursSurvived, isoPlayerPZ.getHoursSurvived_PZ())

    modDataManager.save(pageBook.Character.LIFE_TIME,
            hoursSurvived)
end

return CharacterLifeTime