---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---


---@class CharacterBoost

local CharacterBoost = {}

local characterLib = require("CharacterLib")
local characterPz = require("lib/CharacterPZ")
local dataValidator = require("lib/DataValidator")
local errHandler = require("lib/ErrHandler")
local pageBook = require("PageBook")
local modDataManager = require("lib/ModDataManager")

require("lib/CharacterBaseObj")

---@param perk PerkFactory.Perk
---@param boostLevel int
local lines_ = {}

---@param perk PerkFactory.Perk
---@param int
---@return table perk, int
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactor
local function addlines(perk, boostLevel)
    table.insert(lines_, {
        ---@type PerkFactory.Perk
        perk = perk,

        ---@type int
        boostLevel = boostLevel
    })
end

--- **Read Boost From Hd**
---@return table perk, int
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory
local function readBoostFromHd()
    return modDataManager.read(pageBook.Character.BOOST)
end

--- **Delete Boost**
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function deleteBoost(character)
    -- @type CharacterBaseObj
    local CharacterAllPerksObJ = characterLib.getAllPerks(character)

    for _, v in pairs(CharacterAllPerksObJ:getPerkDetails()) do
        characterPz.removePerkBoost(character, v:getPerk())
    end
end

--- **Create Boost**
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterBoost.readBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterBoost.readBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    --- **check if moddata boost is exits**
    if not modDataManager.isExists(pageBook.Character.BOOST) then
        errHandler.errMsg("CharacterBoost.readBook(character)",
                " moddata " .. pageBook.Character.BOOST .. " " .. errHandler.err.IS_NULL)
        return nil
    end

    ---@type table - PerkFactory.Perk, int (boostlevel)
    local boost = readBoostFromHd()

    --- check if boost is nil
    if not boost then return nil end

    deleteBoost(character)

    -- **Set Boost**
    for _, v in pairs(boost) do
        characterPz.setPerkBoost_PZ(character, v.perk, v.boostLevel)
    end
end

--- **Write Trait To Hd**
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
--- - PerkFactory.Perk : zombie.characters.skills.PerkFactory
function CharacterBoost.writeBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterBoost.writeBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    modDataManager.remove(pageBook.Character.BOOST)

    -- @type CharacterBaseObj
    local CharacterPerksBoostObj = characterLib.getPerksBoost(character)

    for _, v in pairs(CharacterPerksBoostObj:getPerkDetails()) do
        ---@param perk PerkFactory.Perk
        ---@param BoostLevel int
        addlines(v:getPerk(), v:getBoostLevel())
    end

    --- **Save Boost to moddata**
    modDataManager.save(pageBook.Character.BOOST, lines_)

    lines_ = {}

    -- Todo: da controllare, sembra che il ciclo non funzioni
    -- dataValidator.destroyTable(lines_)

    --
    --for i, _ in pairs(lines_) do
    --    table.remove(lines_, i)
    --end
end

return CharacterBoost