---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 24/04/23 09:17
---

---@class CharacterNutrition

local CharacterNutrition = {}

local isoPlayerPZ = require("lib/IsoPlayerPZ")
local pageBook = require("PageBook")
local modDataManager = require("lib/ModDataManager")

local convertToTable = {}

--- **Read Weight From Hd**
---@return table double
local function readWeightFromHd()
    return modDataManager.read(pageBook.Character.WEIGHT)
end

--- **Read Calories From Hd**
---@return table float
local function readCaloriesFromHd()
    return modDataManager.read(pageBook.Character.CALORIES)
end

--- **Write Weight From Hd**
local function writeWeightFromHd()
    table.insert(convertToTable, isoPlayerPZ.getWeight_PZ())
    modDataManager.save(pageBook.Character.WEIGHT,convertToTable )
    convertToTable = {}
end

--- **Write Calories From Hd**
local function writeCaloriesFromHd()
    table.insert(convertToTable, isoPlayerPZ.getCalories_PZ())
    modDataManager.save(pageBook.Character.CALORIES, convertToTable)
    convertToTable = {}
end

--- **Create Character Nutrition**
function CharacterNutrition.readBook()
    if not modDataManager.isExists(pageBook.Character.WEIGHT) then
        return nil
    end

    ---@type table
    ---@return table double
    local weight = {}
    weight = readWeightFromHd()

    for i, v in pairs(weight) do
        isoPlayerPZ.setWeight_PZ(v)
    end

    if not modDataManager.isExists(pageBook.Character.CALORIES) then
        return nil
    end

    ---@type table
    ---@return table float
    local calories = {}
    calories = readCaloriesFromHd()

    for i, v in pairs(calories) do
        isoPlayerPZ.setCalories_PZ(v)
    end
end

--- **Wwrite Character Nutrition**
function CharacterNutrition.writeBook()
    modDataManager.remove(pageBook.Character.WEIGHT)
    modDataManager.remove(pageBook.Character.CALORIES)

    writeWeightFromHd()
    writeCaloriesFromHd()
end

return CharacterNutrition