---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---
require("media.lua.client.EnumModData")
require("media.lua.shared.objects.CharacterObj")

---Read Multiplier From Hd
---@return table
local function readMultiplierFromHd()
    local values = {}
    values = ModData.get(EnumModData.CHARACTER_MULTIPLIER)

   return values
end

---Delete Multiplier
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
local function deleteMultiplier(character)
    local CharacterMultiplierObJ = CharacterObj:new()
    -- CharacterMultiplierObJ = getCharacterAllSkills(character)

    for _, v in pairs(CharacterMultiplierObJ:getPerkDetails()) do
      --  setPerkBoost_PZ(v:getPerk(), EnumNumbers.ZERO)
    end
end

---Create Multiplier
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createMultiplier(character)
    if not modDataIsExist(EnumModData.CHARACTER_MULTIPLIER) then
        return nil
    end

    local boost = {}
    boost = readMultiplierFromHd()

    if not boost then
        return nil
    end

    deleteMultiplier(character)

    for _, v in pairs(boost) do
--        setPerkBoost_PZ(character, v.perk, v.boostLevel)
    end
end

---Write Trait To Hd
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeMultiplierToHd(character)
    ModData.remove(EnumModData.CHARACTER_MULTIPLIER)

    local CharacterMultiplierObJ = CharacterObj:new()
     CharacterMultiplierObJ = getCharacterPerksBoost(character)

    for _, v in pairs(CharacterMultiplierObJ:getPerkDetails()) do

    end

    modDataInsertMultipleValue(EnumModData.CHARACTER_MULTIPLIER, lines_)

    lines_ = {}
end
