---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---
require("media.lua.client.EnumModData")

local lines_ = { perk, boostLevel }

local function lines(perk, boostLevel)
    table.insert(lines_, {
        perk = perk,
        boostLevel = boostLevel
    })
end

---Read Boost From Hd
---@return table
local function readBoostFromHd()
    local values = {}
    values = ModData.get(EnumModData.CHARACTER_BOOST)

   return values
end

---Delete Boost
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
local function deleteBoost(character)
    local CharacterAllSkillsObJ = CharacterObj:new()
    CharacterAllSkillsObJ = getCharacterAllSkills(character)

    for _, v in pairs(CharacterAllSkillsObJ:getPerkDetails()) do
        setPerkBoost_PZ(v:getPerk(), EnumNumbers.ZERO)
    end
end

---Create Boost
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createBoost(character)
    if not modDataIsExist(EnumModData.CHARACTER_BOOST) then
        return nil
    end

    local boost = {}
    boost = readBoostFromHd()

    if not boost then
        return nil
    end

    deleteBoost(character)

    for _, v in pairs(boost) do
        local dbg
        print(tostring(v.perk) .. " - " .. tostring(v.boostLevel))
        setPerkBoost_PZ(character, v.perk, v.boostLevel)
    end
end

---Write Trait To Hd
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeBoostToHd(character)
    ModData.remove(EnumModData.CHARACTER_BOOST)

    local CharacterPerksBoostObj = CharacterObj:new()
    CharacterPerksBoostObj = getCharacterPerksBoost(character)

    for _, v in pairs(CharacterPerksBoostObj:getPerkDetails()) do
        lines(v:getPerk(), v:getBoostLevel())
        print(tostring(v:getPerk()) .. " - " .. tostring(v:getBoostLevel()))
    end

    modDataInsertMultipleValue(EnumModData.CHARACTER_BOOST, lines_)

    lines_ = {}
end