---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

local modDataManager = require("lib/ModDataManager")
local characterPz = require("lib/CharacterPZ")
local characterLib = require("CharacterLib")
require("lib/CharacterBaseObj")

local lines_ = { perk, multiplier }

local function lines(perk, multiplier)
    table.insert(lines_, {
        perk = perk,
        multiplier = multiplier
    })
end

--- **Read Multiplier From Hd**
---@return table
local function readMultiplierFromHd()
    return modDataManager.read(EnumModData.CHARACTER_MULTIPLIER)
end

--- **Delete Multiplier**
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
local function deleteMultiplier(character)
    local CharacterMultiplierObJ = CharacterBaseObj:new()
    CharacterMultiplierObJ = characterLib.getAllPerks(character)

    for _, v in pairs(CharacterMultiplierObJ:getPerkDetails()) do
        characterPz.removeMultiplier(character, v:getPerk())
    end
end

--- **Create Multiplier**
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createMultiplier(character)
    if not modDataManager.isExists(EnumModData.CHARACTER_MULTIPLIER) then
        return nil
    end

    local multiplier = {}
    multiplier = readMultiplierFromHd()

    if not multiplier then
        return nil
    end

    deleteMultiplier(character)

    for _, v in pairs(multiplier) do
        characterPz.addXpMultiplier_PZ(character, v.perk, v.multiplier,
            characterPz.EnumNumbers.ONE, characterPz.EnumNumbers.ONE)
    end
end

--- **Write Trait To Hd**
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function writeMultiplierToHd(character)
    modDataManager.remove(EnumModData.CHARACTER_MULTIPLIER)

    local CharacterMultiplierObJ = CharacterBaseObj:new()
     CharacterMultiplierObJ = characterLib.getMultiplier(character)

    for _, v in pairs(CharacterMultiplierObJ:getPerkDetails()) do
        if v:getMultiplier() > 0.0 then
            lines(v:getPerk(), v:getMultiplier())
        end
    end

    modDataManager.save(EnumModData.CHARACTER_MULTIPLIER, lines_)

    lines_ = {}
end
