---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---
require("media.lua.client.EnumModData")
require("media.lua.shared.objects.CharacterObj")

---Read Recipe From Hd
---@return CharacterObj getRecipes table string
local function readRecipeFromHd()
    local characterKnowRecipe =
         ModData.get(EnumModData.CHARACTER_RECIPES )

    local CharacterObj01 = CharacterObj:new()

    for i, v in pairs(characterKnowRecipe) do
        CharacterObj01:addRecipe(v)
    end

    return CharacterObj01
end

---Delete Trait
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
local function deleteRecipe(character)
    local characterKnowRecipe = CharacterObj:new()

    characterKnowRecipe = getCharacterKnownRecipes(character)

    for _, v in pairs(characterKnowRecipe:getRecipes()) do
        removeKnowRecipes(character, v)
    end
end

---Create Recipe
---@param character IsoGameCharacter
--- - zombie.characters.IsoGameCharacter
function createRecipe(character)
    if not modDataIsExist(EnumModData.CHARACTER_RECIPES) then
        return nil
    end
    local CharacterObj01 = CharacterObj:new()

    CharacterObj01 = readRecipeFromHd(character)
    deleteRecipe(character)

    for i, v in pairs(CharacterObj01:getRecipes()) do
        addKnownRecipes(character, v)
    end
end

---Write Recipe To Hd
function writeRecipeToHd(character)
    local knownRecipesObj = CharacterObj:new()
    knownRecipesObj = getCharacterKnownRecipes(character)

    local lines = {}

    for i, v in pairs(knownRecipesObj:getRecipes()) do
        table.insert(lines, v)
    end

    modDataInsertMultipleValue(EnumModData.CHARACTER_RECIPES, lines)
end