---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

local modDataX = require("lib/ModDataX")

function removeMoData()
    modDataX.remove(EnumModData.CHARACTER_BOOST)
    modDataX.remove(EnumModData.CHARACTER_CALORIES)
    modDataX.remove(EnumModData.CHARACTER_LIFE_TIME)
    modDataX.remove(EnumModData.CHARACTER_PERK_DETAILS)
    modDataX.remove(EnumModData.CHARACTER_PROFESSION)
    modDataX.remove(EnumModData.CHARACTER_TRAITS)
    modDataX.remove(EnumModData.CHARACTER_WEIGHT)
    modDataX.remove(EnumModData.CHARACTER_ZOMBIE_KILLS)
end

---Read Book
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function readBook(character)
    createCharacterPerkDetails(character)
    createZombieKills(character)
    createLifeTime()
    createCharacterNutrition()
    createTrait(character)
    createRecipe(character)
    createBoost(character)
    createMultiplier(character)
     removeMoData()
end

---Write Book
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function writeBook(character)
    writeCharacterPerkDetailsToHd(character)
    writeZombieKillsToHd(character)
    writeLifeTimeToHd()
    writeCharacterNutrition()
    writeTraitToHd(character)
    writeRecipeToHd(character)
    writeBoostToHd(character)
    writeMultiplierToHd(character)
end

