---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 24/04/23 09:17
---

---Read Weight From Hd
local function readWeightFromHd()
    return modDataReadSingleValue( EnumModData.CHARACTER_WEIGHT)
end

---Read Calories From Hd
local function readCaloriesFromHd()
    return modDataReadSingleValue( EnumModData.CHARACTER_CALORIES)
end

---Write Weight From Hd
local function writeWeightFromHd()
    modDataInsertSingleValue(EnumModData.CHARACTER_WEIGHT, getWeight_PZ())
end

---Write Calories From Hd
local function writeCaloriesFromHd()
    modDataInsertSingleValue(EnumModData.CHARACTER_CALORIES, getCalories_PZ())
end

---Create Character Nutrition
function createCharacterNutrition()
    if not modDataIsExist(EnumModData.CHARACTER_WEIGHT) then
        return nil
    end

    local weight = readWeightFromHd()
    setWeight_PZ(weight)

    if not modDataIsExist(EnumModData.CHARACTER_CALORIES) then
        return nil
    end

    local calories = readCaloriesFromHd()
    setCalories_PZ(calories)
end

---Wwrite Character Nutrition
function writeCharacterNutrition()
    writeWeightFromHd()
    writeCaloriesFromHd()
end
