---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

function removeMoData()
    modDataRemove(EnumModData.CHARACTER_BOOST)
    modDataRemove(EnumModData.CHARACTER_CALORIES)
    modDataRemove(EnumModData.CHARACTER_LIFE_TIME)
    modDataRemove(EnumModData.CHARACTER_PERK_DETAILS)
    modDataRemove(EnumModData.CHARACTER_PROFESSION)
    modDataRemove(EnumModData.CHARACTER_TRAITS)
    modDataRemove(EnumModData.CHARACTER_WEIGHT)
    modDataRemove(EnumModData.CHARACTER_ZOMBIE_KILLS)
end

---Read Book
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function readBook(character)
    createCharacterPerkDetails(character) -- ok
    createZombieKills(character) -- ok
    createLifeTime() -- ok
    createCharacterNutrition() -- ok
    createTrait(character) -- ok
    createRecipe(character) -- ok
    createBoost(character)
    -- removeMoData() -- ok
end

---Write Book
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function writeBook(character)
    removeMoData()
    writeCharacterPerkDetailsToHd(character) -- ok
    writeZombieKillsToHd(character) -- ok
    writeLifeTimeToHd() -- ok
    writeCharacterNutrition() -- ok
    writeTraitToHd(character) -- ok
    writeRecipeToHd(character) -- ok
    writeBoostToHd(character)
end

