---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 13:52
---

require("media.lua.shared.objects.CharacterObj")
require("media.lua.client.EnumModData")

---Read Character Perk Details From Hd
---@return CharacterObj getPerkDetails() -- table PerkFactory.Perk perk, int level, float xp
local function readCharacterPerkDetailsFromHd()

    local characterPerkDetails =
        ModData.get(EnumModData.CHARACTER_PERK_DETAILS )

    local lines = {}

    local CharacterObj01 = CharacterObj:new(nil)

    for _, v in pairs(characterPerkDetails) do
        for s in v:gmatch("[^\r-]+") do
            table.insert(lines, s)
        end

        CharacterObj01:addPerkDetails(
                getPerkFromName_PZ(lines[1]),
                tonumber(lines[2]),
                tonumber(lines[3]) + 0.0)


        lines = {}
    end


    lines[1] = ModData.get(EnumModData.PROFESSION )
    CharacterObj01:setProfession(lines[1])

    return CharacterObj01:getPerkDetails()
end

---Delete  all skills Character
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function deleteCharacter(character)
    local CharacterAllSkillsObj = CharacterObj:new(nil)

    CharacterAllSkillsObj = getCharacterAllSkills(character)

    for _, v in pairs(CharacterAllSkillsObj) do
        removePerkLevel(character, v:getPerk())
    end

    setCharacterProfession_PZ("")
end

---Copy Character Skill
---@param character IsoGameCharacter
function createCharacterSkill(character)
    local CharacterAllSkillsObj = CharacterObj:new(nil)
    CharacterAllSkillsObj = readCharacterPerkDetailsFromHd()

    deleteCharacter(character)

    for _, v in pairs(CharacterAllSkillsObj) do
        setPerkLevel(character, v.perk, v.xp)
    end

    setCharacterProfession_PZ( CharacterAllSkillsObj:getProfession() )
end

---Write Character Perk Details To Hd
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function writeCharacterPerkDetailsToHd(character)
    ModData.remove(EnumModData.CHARACTER_PERK_DETAILS )

    local lines = {}

    local CharacterAllSkillsObj = CharacterObj:new(nil)

    CharacterAllSkillsObj = getCharacterAllSkills(character)

    for i, v in pairs(CharacterAllSkillsObj) do
        lines[i] = ( v:getPerk():getName() .. "-" ..
                tostring(v:getlevel())  .. "-" ..
                tostring(v:getXp()) )

        ModData.add(EnumModData.CHARACTER_PERK_DETAILS, lines)
    end

    lines = {}
    table.insert(lines, CharacterAllSkillsObj:getProfession() )

    ModData.add(EnumModData.PROFESSION, lines)
end






