---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 13:52
---

local characterPz = require("lib/CharacterPZ")
local perkFactoryPZ = require("lib/PerkFactoryPZ")
local characterLib = require("CharacterLib")
local modDataX = require("lib/ModDataX")


require("EnumModData")
require("lib/CharacterObj")

---Read Character Perk Details From Hd
---@return CharacterObj PerkFactory.Perk perk, int level, float xp, boolean flag
local function readCharacterPerkDetailsFromHd()
    local characterPerkDetails =
        modDataX.readModata(EnumModData.CHARACTER_PERK_DETAILS )

    local CharacterObj01 = CharacterObj:new()

    local lines = {}

    for _, v in pairs(characterPerkDetails) do
        for s in v:gmatch("[^\r-]+") do
            table.insert(lines, s)
        end

        -- perk, level, xp
        CharacterObj01:addPerkDetails(perkFactoryPZ.getPerkByName_PZ(lines[1]),
                tonumber(lines[2]),
                tonumber(lines[3]) + 0.0)

        lines = {}
    end

    return CharacterObj01
end

---Delete  all skills Character
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function deleteCharacter(character)
    local characterAllSkills = CharacterObj:new()

    characterAllSkills = characterLib.getAllPerks(character)

    for _, v in pairs(characterAllSkills:getPerkDetails()) do
        characterPz.removePerkLevel(character, v:getPerk())
    end

    characterPz.removeProfession(character)
end

---Copy Character Skill
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function createCharacterPerkDetails(character)
    if not modDataX.isExists(EnumModData.CHARACTER_PROFESSION) or not
            modDataX.isExists(EnumModData.CHARACTER_PERK_DETAILS) then
        return nil
    end

    local characterSkills = CharacterObj:new()
    characterSkills = readCharacterPerkDetailsFromHd()

    deleteCharacter(character)

    for _, v in pairs(characterSkills:getPerkDetails()) do
        characterPz.setPerkLevel(character, v:getPerk(), v:getXp())
    end

    local profession = {}
    profession = modDataX.readModata(EnumModData.CHARACTER_PROFESSION)

    characterPz.setProfession_PZ(character,
            profession[1])
end

---Write Character Perk Details To Hd
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function writeCharacterPerkDetailsToHd(character)
    modDataX.remove(EnumModData.CHARACTER_PERK_DETAILS )
    modDataX.remove(EnumModData.CHARACTER_PROFESSION )

    local lines = {}

    local characterAllSkills = CharacterObj:new()
    characterAllSkills = characterLib.getAllPerks(character)

    for _, v in pairs(characterAllSkills:getPerkDetails()) do
        local value = ( v.perk:getName() .. "-" ..
                tostring(v:getLevel())  .. "-" ..
                tostring(v:getXp()) )

        table.insert(lines, value)
    end

    modDataX.saveModata(EnumModData.CHARACTER_PERK_DETAILS, lines)

    lines = {}
    modDataX.saveModata(EnumModData.CHARACTER_PROFESSION,
            characterAllSkills:getProfession() )
end




