---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/04/23 21:20
---

function readBook(character)
    createCharacterSkill(character)
    createKilledZombies(character)

end

function writeBook(character)
    writeCharacterPerkDetailsToHd(character)
    writeKilledZombiesToHd(character)
end
