---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 19/04/23 15:01
---

---@class EnumModData

EnumModData = {
    CHARACTER_PERK_DETAILS = "characterPerkDetails",
    CHARACTER_LIFE_TIME = "characterLifeTime",
    PROFESSION = "characterProfession",
    ZOMBIEKILLS = "characterZombieKills",
    WEIGHT = "weight",
    CALORIES = "calories"
}