---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 19/04/23 15:01
---

---@class EnumModData

EnumModData = {
    CHARACTER_PERK_DETAILS = "characterPerkDetails",
    CHARACTER_TRAITS = "characterTraits",
    CHARACTER_LIFE_TIME = "characterLifeTime",
    CHARACTER_PROFESSION = "characterProfession",
    CHARACTER_ZOMBIE_KILLS = "characterZombieKills",
    CHARACTER_WEIGHT = "characterWeight",
    CHARACTER_CALORIES = "characterCalories",
    CHARACTER_RECIPES = "characterRecipes",
}