---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)


-- ------------------------------------------------------------

-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
-- Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
