---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)

-- Update 1850 - 14-09-2023

--- Go to ReadEraseRewind or EraseRewindContextMenu and search writeBook or readBook