---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 01/02/23 19:11
--- function ISSkillProgressBar:renderPerkRect()
--- ISSkillProgressBar:updateTooltip(lvlSelected)

require("media.lua.shared.DbgLeleLib")

local function onCustomUIKeyPressed(key)
    local character = getPlayer()


    key34(character, key)
    key35(character, key)
    --key36(character, key)
end
-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
---@param character IsoGameCharacter
function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g\n")
        local CharacterObj01 = CharacterObj:new(nil)

        CharacterObj01 = getCharacterAllSkills(character)

        local dbg

        getPlayer():getModData().nomeCane = CharacterObj01
    end
end

---@param character IsoGameCharacter
function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h\n")

        local CharacterObj02 = CharacterObj:new(nil)

        CharacterObj02 = getPlayer():getModData().nomeCane

        local dbg

        for i, v in pairs( getPlayer():getModData().nomeCane ) do
            print(tostring(v.perk) .. "     " .. tostring(v.level))
        end
    end

end

function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = J\n")

    end
end

-- ------------------------------------------------------------

local function copyCharacter(character)
    local CharacterObj01 = CharacterObj:new(nil)
    CharacterObj01 = getCharacterAllSkills(character)

    for i, v in pairs(CharacterObj01) do
        setPerkLevel(character, v:getPerk(), v:getLevel())
    end
end

local function deleteCharacter(character)
    local CharacterObj01 = CharacterObj:new(nil)
    CharacterObj01 = getCharacterAllSkills(character)

    for i, v in pairs(CharacterObj01) do
        removePerkLevel(character, v:getPerk(), _)
    end
end

local function OnGameStart()

end

Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
