---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

local nameModData = "zombieKills"

---Read Zombies Killed From Hd
---@return int
local function readZombieKillsFromHd()
    local lines = {}

    lines = ModData.get(nameModData)
    return lines[1]
end

---Set Zombies Killed
---@param character IsoGameCharacter
---@param killZombies int
local function setZombieKills_PZ(character, killZombies)
    character:setZombieKills(killZombies)
end

---Get Zombies Killed
---@param character IsoGameCharacter
---return int
local function getZombieKills_PZ(character)
    return character:getZombieKills()
end

---Create Zombies Kills
---@param character IsoGameCharacter
function createZombieKills(character)
    local zombieKills = readZombieKillsFromHd()
    setZombieKills_PZ(character, zombieKills)
end

---Write Zombies Kills To Hd
---@param character IsoGameCharacter
function writeZombieKillsToHd(character)
    ModData.remove(nameModData)

    local zombieKills = getZombieKills_PZ(character)

    local lines = {}
    table.insert(lines, zombieKills)

    ModData.add(nameModData, lines)
end