---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

local nameModData = "killedZombies"

---Read Killed Zombies From Hd
---@return int
local function readKilledZombiesFromHd()
    local lines = {}

    lines = ModData.get(nameModData)
    return lines[1]
end

---Set Killed Zombies
---@param character IsoGameCharacter
---@param killedZombies int
local function setKilledZombies(character, killedZombies)
    character:setZombieKills(killedZombies)
end

---Get Killed Zombies
---@param character IsoGameCharacter
---return int
local function getKilledZombies(character)
    return character:getZombieKills()
end

function createKilledZombies(character)
    local killedZombies = readKilledZombiesFromHd()
    setKilledZombies(character, killedZombies)
end

---Write Killed Zombies To Hd
---@param character IsoGameCharacter
function writeKilledZombiesToHd(character)
    ModData.remove(nameModData)

    local killedZombies = getKilledZombies(character)

    local lines = {}
    table.insert(lines, killedZombies)

    ModData.add(nameModData, lines)
end