---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/04/23 17:41
---

require("media.lua.shared.DbgLeleLib")

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key34(character, key)
    key35(character, key)
    key36(character, key)
    key37(character, key)
end

-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > get profession \n")
        -- removeMoData()
        -- writeCharacterPerkDetailsToHd(character) -- ok
        -- writeZombieKillsToHd(character) -- ok
        -- writeLifeTimeToHd() -- ok
        -- writeCharacterNutrition() -- ok
        writeTraitToHd(character) -- no
    end
end

---@param character IsoGameCharacter
function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > set profession \n")
        -- createCharacterPerkDetails(character) -- ok
        -- createZombieKills(character) -- ok
        -- createLifeTime() -- ok
        -- createCharacterNutrition() -- ok
        createTrait(character) -- no
    end
end

---@param character IsoGameCharacter
function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > delete \n")
        removeMoData()
        -- setZombieKills_PZ(character, 15)
    end
end

---@param character IsoGameCharacter
function key37(character, key)
    if key == 37 then -- <<<< j
        print("Key = k > delete \n")
        -- removeMoData()
        -- setZombieKills_PZ(character, 3)
    end
end

-- ------------------------------------------------------------

-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)