---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/04/23 17:41
---

require("media.lua.shared.ProjectZomboidLibs")
require("media.lua.shared.objects.CharacterObj")
require("media.lua.shared.DbgLeleLib")

-- https://theindiestone.com/forums/index.php?/topic/9799-key-code-reference/
local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    if key == 34 then key34(character, key)  end -- <<<< g
    if key == 35 then key35(character, key)  end -- <<<< h
    if key == 36 then key36(character, key)  end -- <<<< j
    if key == 37 then key37(character, key)  end -- <<<< kill
    if key == 16 then key16(character, key)  end -- <<<< 1
    if key == 17 then key17(character, key)  end -- <<<< 2

end

function key16(character, key)
    if key == 16 then -- <<<< g
        print("Key = q > setPerkBoost_PZ) \n")
        -- Perks.Woodwork
        setPerkBoost_PZ(character, Perks.Cooking, 3)
    end
end

---@param character IsoGameCharacter
function key17(character, key)
    if key == 17 then
        print("Key = w > writeBoostToHd) \n")
        setPerkBoost_PZ(character, Perks.Cooking, 0)
    end
end

-- Perks.Cooking
-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > writeBook \n")
        writeBook(character)
    end
end

---@param character IsoGameCharacter
function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > readBook \n")
        readBook(character)
    end
end

---@param character IsoGameCharacter
function key36(character, key)
    if key == 36 then
        print("Key = j > modDataRemove \n")
        modDataRemove(EnumModData.CHARACTER_BOOST)
    end
end

---@param character IsoGameCharacter
function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > delete \n")
        character:die()
    end
end

-- ------------------------------------------------------------
-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)