---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/04/23 17:41
---

require("media.lua.shared.ProjectZomboidLibs")
require("media.lua.shared.objects.CharacterObj")
require("media.lua.shared.DbgLeleLib")

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key34(character, key)
    key35(character, key)
    key36(character, key)
    key37(character, key)
end

-- Perks.Maintenance
-- Perks.Woodwork
-- Perks.Sprinting
-- Todo 		self.character:playSound("CloseBook")
---@param character IsoGameCharacter
function key34(character, key)
    if key == 34 then -- <<<< g
        print("Key = g > get profession \n")

        -- ---@diagnostic disable-next-line
        ---@type CharacterObj
        local CharacterObj01 = CharacterObj:new()

    end
end

---@param character IsoGameCharacter
function key35(character, key)
    if key == 35 then -- <<< h
        print("Key = h > set profession \n")
        ---@type CharacterObj
        local CharacterObj01 = CharacterObj:new()

        CharacterObj01 = getCharacterTraitsPerk(character)

        for i, v in pairs(CharacterObj01:getPerkDetails()) do
            print(v:getPerk())
        end

        print("-------------------------------")

        for i, v in pairs(CharacterObj01:getRecipes()) do
            print(v)
        end

    end
end

---@param character IsoGameCharacter
function key36(character, key)
    if key == 36 then -- <<<< j
        print("Key = j > delete \n")
        -- removeMoData()
        -- setZombieKills_PZ(character, 15)
    end
end

---@param character IsoGameCharacter
function key37(character, key)
    if key == 37 then -- <<<< k
        print("Key = k > delete \n")
        character:die()
    end
end

-- ------------------------------------------------------------
---Get Character Traits
---@param character IsoGameCharacter
---@return CharacterObj table - PerkFactory.Perk perk, int level
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
local function getCharacterTraitsPerkX(character)
    local CharacterObj01 = CharacterObj:new()

    local traits_PZ = getTraitsPerk_PZ(character)

    for i = 0, traits_PZ:size() - 1 do

        ---@type TraitFactory.Trait
        local trait = TraitFactory.getTrait(traits_PZ:get(i) )

        -- print(trait:getType())
        CharacterObj01:addTrait(trait:getType())

        ---@type TraitFactory.Trait
        local traitMap = trait:getXPBoostMap()

        ---@type KahluaTable
        local traitKahluaTable = transformIntoKahluaTable(traitMap)

        for perk, level in pairs(traitKahluaTable) do
            CharacterObj01:addPerkDetails(perk, level:intValue(), nil)
        end
    end

    CharacterObj01:setProfession("cane")
    return CharacterObj01
end
-- ------------------------------------------------------------

local function OnGameStart()

end

-- Events.OnGameStart.Add(OnGameStart)
Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)