---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 07/10/23 12:25
---

---@class OneTimeBookRead

local OneTimeBookRead = {}

local characterManagement = require("CharacterManagement")
local errHandler = require("lib/ErrHandler")

--- **Read Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function OneTimeBookRead.readBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("OneTimeBookRead.readBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    characterManagement.readBook(character)
end

--- **Write Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function OneTimeBookRead.writeBook(character)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("OneTimeBookRead.writeBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    characterManagement.writeBook(character)
end

return OneTimeBookRead