---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 07/10/23 12:25
---

---@class OneTimeBookRead

local OneTimeBookRead = {}

local characterManagement = require("CharacterManagement")

--- **Read Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function OneTimeBookRead.readBook(character)
    characterManagement.readBook(character)
end

--- **Write Book**
---@param character IsoGameCharacter
---@return void
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function OneTimeBookRead.writeBook(character)
    characterManagement.writeBook(character)
end

return OneTimeBookRead