---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 19/04/23 15:01
---

---@class ModData

local ModData = {}

--- **ModData Character**
---@return table string
ModData.Character = {
    BOOST = "characterBoost",
    BOOK_READABLE = "characterBookReadable",
    CALORIES = "characterCalories",
    LIFE_TIME = "characterLifeTime",
    MULTIPLIER = "characterMultiplier",
    PERK_DETAILS = "characterPerkDetails",
    PROFESSION = "characterProfession",
    RECIPES = "characterRecipes",
    TRAITS = "characterTraits",
    WEIGHT = "characterWeight",
    KILLED_ZOMBIES = "characterZombieKills",
}

return ModData