---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 15/04/23 18:54
---

---@class CharacterKilledZombies

local CharacterKilledZombies = {}

local characterPz = require("lib/CharacterPZ")
local errHandler = require("lib/ErrHandler")
-- local pageBook = require("book/PageBook")
local modDataManager = require("lib/ModDataManager")

--- **Read Zombies Killed From Hd**
---@return table int ( killed zombies )
local function readKilledZombiesFromHd(modData_name)
    return modDataManager.read(modData_name.KILLED_ZOMBIES)
end

--- **Create Zombies Kills**
---@param character IsoGameCharacter
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterKilledZombies.readBook(character, modData_name)
    --- **Check if mod-data killedZombies is exits**
    if not modDataManager.isExists(modData_name.KILLED_ZOMBIES) then
        errHandler.errMsg("CharacterKilledZombies.readBook(character)",
                " mod-data " .. modData_name.KILLED_ZOMBIES .. " not exists")
        return nil
    end

    ---@type table
    ---@return int ( killed zombies )
    local killedZombies = readKilledZombiesFromHd(modData_name)

     characterPz.setZombieKills_PZ(character, killedZombies[1])

end

--- **Write Zombies Kills To Hd**
---@param character IsoGameCharacter
---@param modData_name string
--- - IsoGameCharacter : zombie.characters.IsoGameCharacter
function CharacterKilledZombies.writeBook(character, modData_name)
    --- **Check if character is null**
    if not character then
        errHandler.errMsg("CharacterKilledZombies.writeBook(character)",
                errHandler.err.IS_NULL_CHARACTERS)
        return nil
    end

    -- Acquisisce la tabella ModData con il nome specificato
    local temp = modDataManager.read(modData_name)

    if temp then
        -- Ottiene il numero di zombie uccisi
        local killedZombies = characterPz.getZombieKills_PZ(character)

        -- Salva il numero di zombie uccisi direttamente nella chiave KILLED_ZOMBIES
        temp["KILLED_ZOMBIES"] = killedZombies -- add int zombie killed

        -- Salva le modifiche su disco usando il ModDataManager
        modDataManager.save(modData_name, temp)
    else
        print("ModData " .. modData_name .. " doesn't exist")
    end
end


return CharacterKilledZombies